#!/bin/sh
mkdir -p openwrt || true
mkdir -p openwrt.build || true
mkdir -p openwrt.work || true
git clone git@github.com:gbeine/openwrt.git openwrt.base || true
sudo mount -t overlay overlay -o lowerdir=/home/gbeine/openwrt.base,upperdir=/home/gbeine/openwrt.build,workdir=/home/gbeine/openwrt.work /home/gbeine/openwrt
